### ISSUE TITLE
Youtube views

### ISSUE THREAD

**Issue by HaytamFrh** [gekkedev/youlikehitsbot#5]
i noticed that ur bot does the youtube view job but after it ends it doesnt do the next one unless u refresh

**Comment by gekkedev** [comment]
I just tested it and it seems to work for me. Are we talking about the same method (https://www.youlikehits.com/youtubenew2.php)?  
I suggest you [check if popups are blocked](https://www.wikihow.com/Allow-Pop-Ups-for-a-Page-on-Chrome-on-PC-or-Mac) in your browser. Often one popup (first video) will work, but any following popup is easily considered unwanted. https://www.wikihow.com/Allow-Pop-Ups-for-a-Page-on-Chrome-on-PC-or-Mac

**Comment by HaytamFrh** [comment]
alright
